apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wsf2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wsf2
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wsf2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wsf2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wsf2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xbyi-tenant/rhtap-demo-app/hacbs-test-project-wsf2@sha256:fc61cb08a2b4b98f1aee64eb92deb2e28e5ba7320650c861681804b8eb7a76dc
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
